export const FETCH_USER = 'FETCH_USER'
export const RECEIVE_USER = 'RECEIVE_USER'
export const FETCH_SCRUM_POINTS = 'FETCH_SCRUM_POINTS'
export const RECEIVE_SCRUM_POINTS = 'RECEIVE_SCRUM_POINTS'
export const FETCH_TEAM = 'FETCH_TEAM'
export const RECEIVE_TEAM = 'RECEIVE_TEAM'

